spring:
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdflkehp
    password: UupVPce591B7kzw21x5utsGxM10VQ-P4
    virtual-host: kdflkehp
  cloud:
    stream:
      bindings:
        output:
          destination: CorporateDestination

logging:
  level:
    root: ERROR
    org.springframework.cloud.stream: debug


